---
# tasks file for libev

- import_tasks: common.yml

- name: Download libev
  git:
    repo={{ libev_url }}
    dest={{ builddir }}/libev
    version=master
    force=yes

- name: build libev
  shell:
    cd {{ builddir }}/libev;
    ./configure --prefix={{ installdir }};
    make;
    make install
