---
# tasks file for web-caliper

- include_tasks: "{{ server_app }}.yml"
  when: build_server | bool

- include_tasks: "{{ client_app }}.yml"
  when: build_client | bool

- include_tasks: "{{ proxy_app }}.yml"
  when: build_proxy | bool
