---
# tasks file for nginx

- import_tasks: common.yml

- import_tasks: ca.yml

- name: Download nginx
  get_url:
    url={{ nginx_url }}
    dest={{ pkgsdir }}

- name: unarchive nginx
  unarchive:
    src={{ pkgsdir }}/{{ nginx_file }}
    dest={{ builddir }}
    remote_src=yes

- name: build nginx
  shell:
    cd {{ builddir }}/{{ nginx_dir }};
    ./configure --with-http_ssl_module --prefix={{ installdir }};
    make -j{{ ansible_processor_count }};
    make install

- name: Copy nginx service file
  template: src=nginx/nginx.service dest=/lib/systemd/system/nginx.service

- name: Copy nginx configuration for webserver
  template: src=nginx/nginx.conf.{{ test_case }} dest={{ installdir }}/conf/nginx.conf
  notify: restart nginx

- name: http service state
  service: name=nginx state=started enabled=yes
