---
# tasks file for nginx

- name: Download nginx
  get_url:
    url={{ nginx_url }}
    dest={{ pkgsdir }}

- name: unarchive nginx
  unarchive:
    src={{ pkgsdir }}/nginx-1.13.9.tar.gz
    dest={{ builddir }}
    remote_src=yes

- name: build nginx
  shell:
    cd {{ builddir }}/nginx-1.13.9;
    ./configure --with-http_ssl_module --prefix={{ installdir }};
    make -j{{ ansible_processor_count }};
    make install

- name: Copy nginx service file
  template: src=nginx/nginx.service dest=/lib/systemd/system/nginx.service

- name: Copy nginx configuration for webserver
  template: src=nginx/nginx.conf.webserver dest={{ installdir }}/conf/nginx.conf
  notify: restart nginx

- name: http service state
  service: name=nginx state=started enabled=yes
