---
# handlers file for web-caliper
- include_tasks: "{{ server_app }}.yml"
  when: build_server | bool

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart php
  service:
      name=php-fpm
      state=restarted
      enabled=yes
